#!/usr/bin/env bash

if [ $# == 0 ]; then
    exit 3
fi

APP_DIR=`pwd`
PRJ_NAME="${!#}"
AUTHOR=`whoami`

if [[ -d "$APP_DIR/$PRJ_NAME/app" ]]; then
    APP_DIR="$APP_DIR/$PRJ_NAME/app"
else
    mkdir -p "$APP_DIR/$PRJ_NAME/app"
    APP_DIR="$APP_DIR/$PRJ_NAME/app"
fi

cat > "$APP_DIR/.bash_cli" <<EOT
v1
EOT

cat > "$APP_DIR/.author" <<EOT
$AUTHOR
EOT

cat > "$APP_DIR/.version" <<EOT
0.1
EOT

cat > "$APP_DIR/.help" <<EOT
LOREM IPSUM DOLOR SIT AMET
EOT

>&2 echo "Initialized Bash CLI project: $PRJ_NAME."
