#!/usr/bin/env bash

CUR_DIR=`pwd`
APP_DIR="$CUR_DIR"
PRJ_NAME="{{ project_name }}"
AUTHOR=`whoami`

cat > "$HOME/.bash_completion.d/$PRJ_NAME-ctl" <<EOC
source "$CUR_DIR/framework/complete"
complete -F _bash_cli_$PRJ_NAME-ctl $PRJ_NAME-ctl
EOC

if [[ -f "$CUR_DIR/$PRJ_NAME/$PRJ_NAME-ctl" ]]; then
    exit 1
fi
