#!/usr/bin/env bash

APP_DIR=`pwd`
NAME=bcl

INSTALLATION_DIR="$HOME/.local/bin"
BASH_COMPLETION_FILE="$HOME/.bash_completion"
BASH_COMPLETION_DIR="$HOME/.bash_completion.d"
USER=`echo $HOME | sed -e 's/\/.*\///g'`
GROUP=`groups | awk '{print $1}'`

if [[ -f "$APP_DIR/.bash_cli" ]]; then
    APP_DIR=`dirname "$APP_DIR"`
fi

if [[ ! -f "$APP_DIR/app/.bash_cli" ]]; then
    >&2 echo -e "\033[31mYou are not within a Bash CLI project\033[39m"
    >&2 echo "Please change your directory to a valid project or run the init command to set one up."
    exit 1
fi

if [[ ! -d "$INSTALLATION_DIR" ]]; then
    mkdir -p "$INSTALLATION_DIR"
fi

if [[ ! -d "$BASH_COMPLETION_DIR" ]]; then
    mkdir -p "$BASH_COMPLETION_DIR"
fi

ln -s "$APP_DIR/cli" "$INSTALLATION_DIR/$NAME"
cat > "$BASH_COMPLETION_DIR/$NAME" <<EOC
source "$APP_DIR/complete"
complete -F _bash_cli $NAME
EOC
chown -R $USER:$GROUP $BASH_COMPLETION_DIR

if [[ -f "$BASH_COMPLETION_FILE" ]]; then
    exit 1
fi

cat > "$BASH_COMPLETION_FILE" <<EOC
for BCFILE in ~/.bash_completion.d/* ; do
source \$BCFILE
done
EOC
chown $USER:$GROUP $BASH_COMPLETION_FILE
