#!/usr/bin/env bash

if [ $# == 0 ]; then
    exit 3
fi

CUR_DIR=$(pwd)
APP_DIR="$CUR_DIR"
PRJ_NAME="${!#}"
SUFFIX="ctl"
AUTOCOMPLETE_DIR="$CUR_DIR/$PRJ_NAME/app/autocomplete"
AUTHOR=$(whoami)

mkdir -p "$CUR_DIR/$PRJ_NAME/blueprint"
mkdir -p "$CUR_DIR/$PRJ_NAME/files"
mkdir -p "$CUR_DIR/$PRJ_NAME/framework"
mkdir -p "$CUR_DIR/$PRJ_NAME/playbook"
cp $(ls -alh $HOME/.local/bin/bcl | awk '{print $11}' | sed 's/\/cli/\/framework\//g')* "$CUR_DIR/$PRJ_NAME/framework"

cat > "$CUR_DIR/$PRJ_NAME/BUILD" <<EOC
$PRJ_NAME-v0.0.0-release
git@github.com:sample-organization/sample-package.git
EOC

sed -i.bak "s/{{ function_name }}/_bash_cli_$PRJ_NAME$SUFFIX/g" "$CUR_DIR/$PRJ_NAME/framework/complete"
rm "$CUR_DIR/$PRJ_NAME/framework/complete.bak"

sed -i.bak "s/{{ project_name }}/$PRJ_NAME/g" "$CUR_DIR/$PRJ_NAME/framework/complete"
rm "$CUR_DIR/$PRJ_NAME/framework/complete.bak"

sed -i.bak "s/{{ project_name }}/$PRJ_NAME/g" "$CUR_DIR/$PRJ_NAME/framework/help"
rm "$CUR_DIR/$PRJ_NAME/framework/help.bak"

sed -i.bak "s/{{ project_name }}/$PRJ_NAME/g" "$CUR_DIR/$PRJ_NAME/framework/cli"
rm "$CUR_DIR/$PRJ_NAME/framework/cli.bak"

if [[ -d "$CUR_DIR/$PRJ_NAME/app" ]]; then
    APP_DIR="$APP_DIR/$PRJ_NAME/app"
else
    mkdir -p "$APP_DIR/$PRJ_NAME/app"
    APP_DIR="$APP_DIR/$PRJ_NAME/app"
fi

mkdir -p "$APP_DIR/autocomplete"
cp $(ls -alh $HOME/.local/bin/bcl | awk '{print $11}' | sed 's/\/cli/\/autocomplete\//g')* "$APP_DIR/autocomplete"

sed -i.bak "s/{{ project_name }}/$PRJ_NAME/g" "$APP_DIR/autocomplete/apply"
rm "$APP_DIR/autocomplete/apply.bak"

sed -i.bak "s/{{ project_name }}/$PRJ_NAME/g" "$APP_DIR/autocomplete/remove"
rm "$APP_DIR/autocomplete/remove.bak"

cat > "$APP_DIR/.bash_cli" <<EOT
v1
EOT

cat > "$APP_DIR/.author" <<EOT
$AUTHOR
EOT

cat > "$APP_DIR/.version" <<EOT
0.1
EOT

cat > "$APP_DIR/.help" <<EOT
LOREM IPSUM DOLOR SIT AMET
EOT

cat > "$HOME/.bash_completion.d/$PRJ_NAME$SUFFIX" <<EOC
source "$CUR_DIR/$PRJ_NAME/framework/complete"
complete -F _bash_cli_$PRJ_NAME$SUFFIX $PRJ_NAME$SUFFIX
EOC

>&2 echo "Initialized Bash CLI project: $PRJ_NAME."

if [[ -f "$CUR_DIR/$PRJ_NAME/$PRJ_NAME$SUFFIX" ]]; then
    exit 1
fi

# Render the *ctl entrypoint
mv "$CUR_DIR/$PRJ_NAME/framework/entrypoint" "$CUR_DIR/$PRJ_NAME$SUFFIX"
sed -i.bak "s/{{ project_name }}/$PRJ_NAME/g" "$CUR_DIR/$PRJ_NAME$SUFFIX"
rm "$CUR_DIR/$PRJ_NAME$SUFFIX.bak"

chmod +x "$CUR_DIR/$PRJ_NAME$SUFFIX"
