#!/usr/bin/env bash

# shellcheck disable=SC1090
set -e

source "$ROOT_DIR"/app/.helper/package

APP_DIR=$(pwd)
CACHE_DIRECTORY="${HOME}/.bcl/cache"
BCLFILE="bcl.json"
GITHUB_URL="https://github.com"

function get_package_list_from_file () {
  jq -r ".package | keys[]" $BCLFILE
}

function get_package_version_from_file () {
  jq -r ".package | .\"$1\"" $BCLFILE
}

function install_package_from_repository () {
  for item in $( get_package_list_from_file ); do
    _file_name=$(get_package_version_from_file "$item")
    _package_folder=$( echo "$item" | cut -d "/" -f2 )
    _package_folder+="-$(get_package_version_from_file "$item")"
    curl -Lksf -o "$CACHE_DIRECTORY/${_package_folder}.zip" \
      "${GITHUB_URL}/${item}/archive/${_file_name}.zip"
    __error_code="$?"
    unzip -o "$CACHE_DIRECTORY/${_package_folder}.zip" -d "$CACHE_DIRECTORY" > /dev/null
    __error_code=$((__error_code + $?))
    cp -r "$CACHE_DIRECTORY/$_package_folder/" ./cli
    __error_code=$((__error_code + $?))
    if [[ $__error_code -eq "0" ]]; then
      echo "[*] $item package with verion $_package_folder installed succesfully"
    else
      echo "[ ] $item package not installed"
    fi
  done
}

if [[ ! -f "$APP_DIR/bcl.json" ]]; then
    exit 0
fi

if [[ ! -d "$CACHE_DIRECTORY" ]]; then
  mkdir -p "$CACHE_DIRECTORY"
fi

install_package_from_repository
